kind: pipeline
type: kubernetes
name: juju-test2

metadata:
  namespace: drone

steps:
- name: juju
  image: jujusolutions/jujubox:latest
  environment:
    REGISTER_TOKEN:
      from_secret: juju-drone-register
  commands:
  - set -x
  - juju register ${REGISTER_TOKEN}