kind: pipeline
type: kubernetes
name: juju-test2

metadata:
  namespace: drone

steps:
- name: juju
  image: jujusolutions/jujubox:latest
  environment:
    BOBO: -a
    REGISTER_TOKEN:
      from_secret: juju-drone-register
  commands:
  - set -x
  - ls $${BOBO}
  - juju register $${REGISTER_TOKEN}