kind: pipeline
type: kubernetes
name: juju-test

metadata:
  namespace: drone

steps:
- name: juju
  image: jujusolutions/jujubox:latest
  environment:
    REGISTER_TOKEN:
      from_secret: juju-drone-register
  commands:
  - juju register $REGISTER_TOKEN