kind: pipeline
type: kubernetes
name: juju-test2

metadata:
  namespace: drone

steps:
- name: juju
  image: jujusolutions/jujubox:latest
  environment:
    DRONECI_PASSWD:
      from_secret: juju-droneci-passwd
  commands:
  - echo $${DRONECI_PASSWD} | juju login juju.lab-linux.com -u droneci
  - juju switch drone-minecraft-demo
  - juju deploy postgresql
  - juju deploy charms/minetest-server --series bionic
  - juju add-relation postgresql:db minetest-server:db